// Bitcoin Events Data - Real Events for 2025
// Each event now includes coordinates for map display
const eventsData = [
  {
    id: 1,
    name: "Bitcoin Medellin",
    date: "2025-01-17",
    endDate: "2025-01-18",
    type: "conference",
    location: "Medellin, Colombia",
    coordinates: { lat: 6.2476, lng: -75.5658 },
    description: "Bitcoin conference in Medellin bringing together the Latin American Bitcoin community for education, networking, and adoption discussions.",
    website: "https://btcmedellin.com/",
    x: "https://x.com/BTCMedellinConf",
    nostr: "https://njump.me/npub18g7v9pk2xzmynmu0up65fvejxqz552q5h5l46h2x3vwgjkfn8qnsfq4m9p",
    featured: false
  },
  {
    id: 2,
    name: "Adopting Bitcoin Cape Town",
    date: "2025-01-24",
    endDate: "2025-01-25",
    type: "conference",
    location: "Cape Town, South Africa",
    coordinates: { lat: -33.9249, lng: 18.4241 },
    description: "African Bitcoin conference focused on adoption, education, and building the Bitcoin ecosystem across the continent.",
    website: "https://za25.adoptingbitcoin.org/",
    x: "https://x.com/adoptingbtc",
    nostr: "",
    featured: false
  },
  {
    id: 3,
    name: "Plan ₿ Forum El Salvador",
    date: "2025-01-30",
    endDate: "2025-01-31",
    type: "conference",
    location: "San Salvador, El Salvador",
    coordinates: { lat: 13.6929, lng: -89.2182 },
    description: "Bitcoin conference in El Salvador, the first country to adopt Bitcoin as legal tender. Focus on adoption, regulation, and innovation.",
    website: "https://planb.sv/",
    x: "https://x.com/LuganoPlanB",
    nostr: "",
    featured: false
  },
  {
    id: 4,
    name: "bitcoin++ levels up",
    date: "2025-02-19",
    endDate: "2025-02-22",
    type: "conference",
    location: "Florianopolis, Brasil",
    coordinates: { lat: -27.5969, lng: -48.5495 },
    description: "Technical Bitcoin conference focused on development, innovation, and advancing the Bitcoin protocol. Brings together developers and researchers.",
    website: "https://btcplusplus.dev/conf/floripa",
    x: "https://x.com/btcplusplus",
    nostr: "",
    featured: false
  },
  {
    id: 5,
    name: "Bitcoin Freedom Festival",
    date: "2025-02-23",
    endDate: "2025-02-24",
    type: "conference",
    location: "Uvita, Costa Rica",
    coordinates: { lat: 9.1499, lng: -83.7534 },
    description: "Bitcoin conference in the beautiful coastal town of Uvita, focusing on freedom, adoption, and the Bitcoin lifestyle.",
    website: "https://www.bitcoinfreedomfestival.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 6,
    name: "Mining Conference",
    date: "2025-04-03",
    endDate: "2025-04-04",
    type: "conference",
    location: "Dubai, UAE",
    coordinates: { lat: 25.2048, lng: 55.2708 },
    description: "Global Bitcoin mining conference covering mining operations, hardware, energy, and the future of Bitcoin mining.",
    website: "https://miningconf.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 7,
    name: "BitBlockBoom",
    date: "2025-04-04",
    endDate: "2025-04-05",
    type: "conference",
    location: "Dallas, Texas, USA",
    coordinates: { lat: 32.7767, lng: -96.7970 },
    description: "Bitcoin conference in Dallas focusing on business adoption, investment, and the economic impact of Bitcoin.",
    website: "https://bitblockboom.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 8,
    name: "CheatCode",
    date: "2025-04-11",
    endDate: "2025-04-13",
    type: "conference",
    location: "Bedford, UK",
    coordinates: { lat: 52.1354, lng: -0.4666 },
    description: "Bitcoin conference in the UK focusing on education, adoption, and building the Bitcoin community across Britain.",
    website: "https://www.cheatcode.co.uk/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 9,
    name: "Bitcoin Oasis",
    date: "2025-04-15",
    endDate: "2025-04-17",
    type: "conference",
    location: "Dubai, UAE",
    coordinates: { lat: 25.2048, lng: 55.2708 },
    description: "Bitcoin conference in Dubai focusing on Middle Eastern adoption, regulation, and the intersection of traditional finance with Bitcoin.",
    website: "https://bitcoin-oasis.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 10,
    name: "Swiss Bitcoin Conference",
    date: "2025-04-24",
    endDate: "2025-04-27",
    type: "conference",
    location: "Zurich, Switzerland",
    coordinates: { lat: 47.3769, lng: 8.5417 },
    description: "Major Bitcoin conference in Switzerland, bringing together European Bitcoin enthusiasts, developers, and businesses.",
    website: "https://swiss-bitcoin-conference.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 11,
    name: "Tuscany Summit",
    date: "2025-05-07",
    endDate: "2025-05-08",
    type: "conference",
    location: "Viareggio, Italy",
    coordinates: { lat: 43.8731, lng: 10.2338 },
    description: "Bitcoin conference in the beautiful Tuscany region of Italy, focusing on European adoption and community building.",
    website: "",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 12,
    name: "Bitcoin++",
    date: "2025-05-07",
    endDate: "2025-05-09",
    type: "conference",
    location: "Austin, Texas, USA",
    coordinates: { lat: 30.2672, lng: -97.7431 },
    description: "Technical Bitcoin conference in Austin, bringing together developers, researchers, and innovators to advance Bitcoin technology.",
    website: "https://btcplusplus.dev/",
    x: "https://x.com/btcplusplus",
    nostr: "",
    featured: false
  },
  {
    id: 13,
    name: "Bitcoin Film Fest",
    date: "2025-05-23",
    endDate: "2025-05-25",
    type: "conference",
    location: "Warsaw, Poland",
    coordinates: { lat: 52.2297, lng: 21.0122 },
    description: "Bitcoin conference combined with film festival, showcasing Bitcoin documentaries and educational content in Poland.",
    website: "",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 14,
    name: "Oslo Freedom Forum",
    date: "2025-05-26",
    endDate: "2025-05-28",
    type: "conference",
    location: "Oslo, Norway",
    coordinates: { lat: 59.9139, lng: 10.7522 },
    description: "Human rights and freedom conference that includes Bitcoin as a tool for financial freedom and human rights.",
    website: "https://oslofreedomforum.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 15,
    name: "Bitcoin 2025",
    date: "2025-05-27",
    endDate: "2025-05-29",
    type: "conference",
    location: "Las Vegas, Nevada, USA",
    coordinates: { lat: 36.1699, lng: -115.1398 },
    description: "The world's largest Bitcoin conference, featuring over 15,000 attendees, industry leaders, and comprehensive Bitcoin education.",
    website: "https://b.tc/conference/2025",
    x: "https://x.com/TheBitcoinConf",
    nostr: "",
    featured: true
  },
  {
    id: 16,
    name: "BCC8333",
    date: "2025-06-06",
    endDate: "2025-06-07",
    type: "conference",
    location: "Barcelona, Spain",
    coordinates: { lat: 41.3851, lng: 2.1734 },
    description: "Bitcoin conference in Barcelona focusing on European adoption, development, and community building.",
    website: "https://tickets.bcc8333.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 17,
    name: "BTC Prague",
    date: "2025-06-19",
    endDate: "2025-06-21",
    type: "conference",
    location: "Prague, Czech Republic",
    coordinates: { lat: 50.0755, lng: 14.4378 },
    description: "Bitcoin conference in Prague, bringing together the Central European Bitcoin community for education and networking.",
    website: "https://btcprague.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 18,
    name: "Bitcoin Rodeo",
    date: "2025-06-28",
    endDate: "2025-06-29",
    type: "conference",
    location: "Calgary, Alberta, Canada",
    coordinates: { lat: 51.0447, lng: -114.0719 },
    description: "Bitcoin conference in Calgary with a Western theme, focusing on Canadian adoption and the Bitcoin community.",
    website: "https://bitcoinrodeo.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 19,
    name: "Bitcoin Alaska",
    date: "2025-07-01",
    endDate: "2025-07-06",
    type: "conference",
    location: "Juneau, Alaska, USA",
    coordinates: { lat: 58.3019, lng: -134.4197 },
    description: "Week-long Bitcoin conference in Alaska, combining Bitcoin education with the natural beauty of the Last Frontier.",
    website: "https://bitcoinalaska.org/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 20,
    name: "Mallorca Blockchain Days",
    date: "2025-07-10",
    endDate: "2025-07-13",
    type: "conference",
    location: "Mallorca, Spain",
    coordinates: { lat: 39.6953, lng: 3.0176 },
    description: "Blockchain and Bitcoin conference on the beautiful island of Mallorca, focusing on European adoption and innovation.",
    website: "",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 21,
    name: "bitcoin++ goes private",
    date: "2025-08-07",
    endDate: "2025-08-08",
    type: "conference",
    location: "Riga, Latvia",
    coordinates: { lat: 56.9496, lng: 24.1052 },
    description: "Private Bitcoin conference in Riga, focusing on technical discussions and development in an intimate setting.",
    website: "https://btcplusplus.dev/",
    x: "https://x.com/btcplusplus",
    nostr: "",
    featured: false
  },
  {
    id: 22,
    name: "Baltic Honey Badger",
    date: "2025-08-09",
    endDate: "2025-08-10",
    type: "conference",
    location: "Riga, Latvia",
    coordinates: { lat: 56.9496, lng: 24.1052 },
    description: "Bitcoin conference in the Baltic region, bringing together Eastern European Bitcoin enthusiasts and developers.",
    website: "https://baltichoneybadger.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 23,
    name: "BTChel Conference 2025",
    date: "2025-08-15",
    endDate: "2025-08-16",
    type: "conference",
    location: "Helsinki, Finland",
    coordinates: { lat: 60.1699, lng: 24.9384 },
    description: "Bitcoin conference in Helsinki, focusing on Nordic adoption and the intersection of technology and Bitcoin.",
    website: "https://btchel.com",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 24,
    name: "bitcoin++ scales",
    date: "2025-09-03",
    endDate: "2025-09-05",
    type: "conference",
    location: "Istanbul, Turkey",
    coordinates: { lat: 41.0082, lng: 28.9784 },
    description: "Bitcoin scaling conference in Istanbul, focusing on Layer 2 solutions, Lightning Network, and Bitcoin scalability.",
    website: "https://btcplusplus.dev/",
    x: "https://x.com/btcplusplus",
    nostr: "",
    featured: false
  },
  {
    id: 25,
    name: "lightning++ strikes",
    date: "2025-10-02",
    endDate: "2025-10-04",
    type: "conference",
    location: "Berlin, Germany",
    coordinates: { lat: 52.5200, lng: 13.4050 },
    description: "Lightning Network focused conference in Berlin, bringing together developers and enthusiasts of Bitcoin's Layer 2 solution.",
    website: "https://btcplusplus.dev/",
    x: "https://x.com/btcplusplus",
    nostr: "",
    featured: false
  },
  {
    id: 26,
    name: "BitcoinForum Bayern",
    date: "2025-10-09",
    endDate: "2025-10-11",
    type: "conference",
    location: "Bayern, Germany",
    coordinates: { lat: 48.7904, lng: 11.4979 },
    description: "Regional Bitcoin conference in Bavaria, Germany, focusing on local adoption and community building.",
    website: "https://bitcoinforum.bayern",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 27,
    name: "BTC Balkans",
    date: "2025-10-18",
    endDate: "2025-10-19",
    type: "conference",
    location: "Sofia, Bulgaria",
    coordinates: { lat: 42.6977, lng: 23.3219 },
    description: "Bitcoin conference in the Balkans region, bringing together Southeastern European Bitcoin communities.",
    website: "https://www.btcbalkans.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 28,
    name: "Plan B Forum",
    date: "2025-10-24",
    endDate: "2025-10-25",
    type: "conference",
    location: "Lugano, Switzerland",
    coordinates: { lat: 46.0037, lng: 8.9511 },
    description: "Bitcoin conference in Lugano, Switzerland, focusing on adoption, regulation, and the future of Bitcoin in Europe.",
    website: "https://planb.lugano.ch/planb-forum/",
    x: "https://x.com/LuganoPlanB",
    nostr: "",
    featured: false
  },
  {
    id: 29,
    name: "Sats Conf",
    date: "2025-11-07",
    endDate: "2025-11-08",
    type: "conference",
    location: "Sao Paulo, Brazil",
    coordinates: { lat: -23.5505, lng: -46.6333 },
    description: "Bitcoin conference in Sao Paulo, focusing on Brazilian adoption and the Latin American Bitcoin ecosystem.",
    website: "https://satsconf.com.br/",
    x: "https://x.com/satsconf",
    nostr: "",
    featured: false
  },
  {
    id: 30,
    name: "Bitcoin Amsterdam",
    date: "2025-11-13",
    endDate: "2025-11-14",
    type: "conference",
    location: "Amsterdam, Netherlands",
    coordinates: { lat: 52.3676, lng: 4.9041 },
    description: "European Bitcoin conference in Amsterdam, bringing together the continental Bitcoin community for education and networking.",
    website: "https://www.bitcoin.amsterdam/",
    x: "https://x.com/TheBitcoinConf",
    nostr: "",
    featured: false
  },
  {
    id: 31,
    name: "Adopting Bitcoin El Salvador",
    date: "2025-11-14",
    endDate: "2025-11-15",
    type: "conference",
    location: "San Salvador, El Salvador",
    coordinates: { lat: 13.6929, lng: -89.2182 },
    description: "Bitcoin adoption conference in El Salvador, focusing on the country's experience as the first Bitcoin nation.",
    website: "https://sv25.adoptingbitcoin.org/",
    x: "https://x.com/adoptingbtc",
    nostr: "",
    featured: true
  },
  {
    id: 32,
    name: "Noderunners Conference",
    date: "2025-11-01",
    endDate: "2025-11-01",
    type: "conference",
    location: "Amsterdam, Netherlands",
    coordinates: { lat: 52.3676, lng: 4.9041 },
    description: "Bitcoin node operation and infrastructure conference in Amsterdam, focusing on running Bitcoin nodes and network security.",
    website: "https://noderunners.network/en/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 33,
    name: "BitFest",
    date: "2025-11-21",
    endDate: "2025-11-23",
    type: "conference",
    location: "Manchester, UK",
    coordinates: { lat: 53.4808, lng: -2.2426 },
    description: "Bitcoin festival and conference in Manchester, bringing together the UK Bitcoin community for education, networking, and celebration.",
    website: "https://bitfest.uk/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 34,
    name: "La Bitconf",
    date: "2025-11-07",
    endDate: "2025-11-08",
    type: "conference",
    location: "Buenos Aires, Argentina",
    coordinates: { lat: -34.6118, lng: -58.3960 },
    description: "Bitcoin conference in Buenos Aires, bringing together the Latin American Bitcoin community for education, networking, and adoption discussions.",
    website: "https://labitconf.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 35,
    name: "Watchout Bitcoin",
    date: "2025-10-03",
    endDate: "2025-10-05",
    type: "conference",
    location: "Madrid, Spain",
    coordinates: { lat: 40.4168, lng: -3.7038 },
    description: "Bitcoin conference in Madrid, focusing on European adoption, regulation, and the future of Bitcoin in Spain and the Iberian Peninsula.",
    website: "https://wobitcoin.org/",
    x: "https://x.com/wobitcoin",
    nostr: "",
    featured: false
  },
  {
    id: 36,
    name: "Bitcoin Day Naples",
    date: "2025-01-18",
    endDate: "2025-01-18",
    type: "meetup",
    location: "Naples, Florida, USA",
    coordinates: { lat: 26.1420, lng: -81.7948 },
    description: "Bitcoin meetup in Naples, Florida bringing together local Bitcoin enthusiasts for education, networking, and community building.",
    website: "https://bitcoinday.io",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 37,
    name: "Nashville Energy & Mining Summit",
    date: "2025-01-30",
    endDate: "2025-01-31",
    type: "conference",
    location: "Nashville, Tennessee, USA",
    coordinates: { lat: 36.1627, lng: -86.7816 },
    description: "Energy and mining conference in Nashville focusing on Bitcoin mining operations, renewable energy integration, and sustainable mining practices.",
    website: "https://www.meetup.com/bitcoinpark/events/304092624/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 38,
    name: "Bitcoin Investor Week",
    date: "2025-02-25",
    endDate: "2025-02-28",
    type: "conference",
    location: "New York City, New York, USA",
    coordinates: { lat: 40.7128, lng: -74.0060 },
    description: "Week-long Bitcoin investment conference in NYC bringing together investors, analysts, and financial professionals to discuss Bitcoin investment strategies.",
    website: "https://lu.ma/bitcoininvestorweek",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 39,
    name: "Bitcoin Renaissance",
    date: "2025-02-27",
    endDate: "2025-02-28",
    type: "conference",
    location: "Denver, Colorado, USA",
    coordinates: { lat: 39.7392, lng: -104.9903 },
    description: "Bitcoin Renaissance conference in Denver focusing on the rebirth and evolution of Bitcoin, bringing together innovators and thought leaders.",
    website: "https://bitcoin-renaissance.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 40,
    name: "Bitcoin Ski Summit",
    date: "2025-03-05",
    endDate: "2025-03-09",
    type: "conference",
    location: "Teton Village, Wyoming, USA",
    coordinates: { lat: 43.5876, lng: -110.8278 },
    description: "Unique Bitcoin conference in the mountains combining Bitcoin education with outdoor activities in the beautiful Teton Village ski resort.",
    website: "https://www.apres.tech/bitcoin-ski-summit-2024",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 41,
    name: "Bitcoin Alive",
    date: "2025-03-08",
    endDate: "2025-03-08",
    type: "conference",
    location: "Sydney, Australia",
    coordinates: { lat: -33.8688, lng: 151.2093 },
    description: "Bitcoin Alive conference in Sydney bringing the Bitcoin ecosystem to life through education, networking, and community engagement.",
    website: "https://bitcoinalive.io/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 42,
    name: "BTC Vortex",
    date: "2025-03-09",
    endDate: "2025-03-16",
    type: "conference",
    location: "Miami, Florida, USA",
    coordinates: { lat: 25.7617, lng: -80.1918 },
    description: "Extended Bitcoin conference in Miami creating a vortex of Bitcoin knowledge, innovation, and community building over a full week.",
    website: "https://btcvortex.com",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 43,
    name: "Bitcoin Takeover",
    date: "2025-03-14",
    endDate: "2025-03-14",
    type: "conference",
    location: "Austin, Texas, USA",
    coordinates: { lat: 30.2672, lng: -97.7431 },
    description: "Bitcoin Takeover conference in Austin focusing on how Bitcoin is taking over traditional financial systems and creating new opportunities.",
    website: "https://bitcoin-takeover.org/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 44,
    name: "Bush Bash",
    date: "2025-03-28",
    endDate: "2025-03-30",
    type: "conference",
    location: "Beechworth, Australia",
    coordinates: { lat: -36.3583, lng: 146.6869 },
    description: "Bush Bash Bitcoin conference in the Australian bush bringing together Bitcoin enthusiasts for a unique outdoor conference experience.",
    website: "https://bitcoinbushbash.info/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 45,
    name: "Opt Out Conf",
    date: "2025-03-29",
    endDate: "2025-03-29",
    type: "conference",
    location: "Buenos Aires, Argentina",
    coordinates: { lat: -34.6118, lng: -58.3960 },
    description: "Opt Out Conf in Buenos Aires focusing on opting out of traditional financial systems and embracing Bitcoin alternatives.",
    website: "https://optoutconf.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 46,
    name: "MIT Bitcoin Expo",
    date: "2025-04-05",
    endDate: "2025-04-06",
    type: "conference",
    location: "Cambridge, Massachusetts, USA",
    coordinates: { lat: 42.3736, lng: -71.1097 },
    description: "MIT Bitcoin Expo at the prestigious Massachusetts Institute of Technology, bringing together academic research and Bitcoin innovation.",
    website: "https://mitbtcexpo.org/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 47,
    name: "Bitcoin Strategic Reserve Summit",
    date: "2025-04-15",
    endDate: "2025-04-15",
    type: "conference",
    location: "Online",
    coordinates: null,
    description: "Online summit focusing on Bitcoin as a strategic reserve asset for nations, corporations, and institutional investors.",
    website: "https://bitcoinreservesummit.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 48,
    name: "OPNEXT",
    date: "2025-04-11",
    endDate: "2025-04-12",
    type: "conference",
    location: "Tysons, Virginia, USA",
    coordinates: { lat: 38.9185, lng: -77.2311 },
    description: "OPNEXT conference focusing on the next generation of Bitcoin operations, development, and innovation.",
    website: "https://opnext.dev/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 49,
    name: "Bitcoin for Corporations [MicroStrategy World]",
    date: "2025-05-06",
    endDate: "2025-05-07",
    type: "conference",
    location: "Las Vegas, Nevada, USA",
    coordinates: { lat: 36.1699, lng: -115.1398 },
    description: "MicroStrategy World conference focusing on Bitcoin adoption for corporations, featuring insights from companies leading Bitcoin treasury adoption.",
    website: "https://www.microstrategy.com/en/events/world",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 50,
    name: "BitCare Forum",
    date: "2025-05-10",
    endDate: "2025-05-10",
    type: "conference",
    location: "Brescia, Italy",
    coordinates: { lat: 45.5416, lng: 10.2118 },
    description: "BitCare Forum in Brescia focusing on Bitcoin care, community support, and building sustainable Bitcoin ecosystems.",
    website: "https://bitcareforum.it/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 51,
    name: "Pizza Day Prague",
    date: "2025-05-22",
    endDate: "2025-05-22",
    type: "meetup",
    location: "Prague, Czech Republic",
    coordinates: { lat: 50.0755, lng: 14.4378 },
    description: "Pizza Day celebration in Prague commemorating the famous Bitcoin pizza transaction, bringing together the local Bitcoin community.",
    website: "https://pizzaday.cz/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 52,
    name: "Bitcoin Ireland Conference",
    date: "2025-05-24",
    endDate: "2025-05-24",
    type: "conference",
    location: "Dublin, Ireland",
    coordinates: { lat: 53.3498, lng: -6.2603 },
    description: "Bitcoin Ireland Conference bringing together the Irish Bitcoin community for education, networking, and adoption discussions.",
    website: "https://www.bitcoinireland.eu/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 53,
    name: "Bitcoin Economic Forum",
    date: "2025-05-30",
    endDate: "2025-06-01",
    type: "conference",
    location: "Bretagne, France",
    coordinates: { lat: 48.2020, lng: -2.9326 },
    description: "Bitcoin Economic Forum in Bretagne focusing on the economic implications of Bitcoin adoption and its impact on regional economies.",
    website: "https://www.breizhbitcoin.com/bitcoin-economic-forum/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 54,
    name: "Bitcoin Seoul Conference",
    date: "2025-06-04",
    endDate: "2025-06-06",
    type: "conference",
    location: "Seoul, South Korea",
    coordinates: { lat: 37.5665, lng: 126.9780 },
    description: "Bitcoin Seoul Conference bringing together the Korean Bitcoin community for education, networking, and adoption discussions.",
    website: "http://bitcoinseoul.kr",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 55,
    name: "Bitcoin Day Tampa",
    date: "2025-06-14",
    endDate: "2025-06-14",
    type: "meetup",
    location: "Tampa, Florida, USA",
    coordinates: { lat: 27.9506, lng: -82.4572 },
    description: "Bitcoin Day meetup in Tampa bringing together local Bitcoin enthusiasts for education and community building.",
    website: "https://bitcoinday.io",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 56,
    name: "Sound Money Soiree",
    date: "2025-06-14",
    endDate: "2025-06-14",
    type: "meetup",
    location: "Tampa, Florida, USA",
    coordinates: { lat: 27.9506, lng: -82.4572 },
    description: "Sound Money Soiree in Tampa celebrating sound money principles and Bitcoin adoption in the local community.",
    website: "https://www.bitcoinbay.live/sound-money-soiree",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 57,
    name: "Bitcoin Corporate Day",
    date: "2025-06-20",
    endDate: "2025-06-20",
    type: "conference",
    location: "Prague, Czech Republic",
    coordinates: { lat: 50.0755, lng: 14.4378 },
    description: "Bitcoin Corporate Day in Prague focusing on corporate Bitcoin adoption, treasury management, and business integration.",
    website: "https://www.bitcoincorporateday.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 58,
    name: "Bitcoin Policy Institute Summit",
    date: "2025-06-25",
    endDate: "2025-06-25",
    type: "conference",
    location: "Washington DC, USA",
    coordinates: { lat: 38.9072, lng: -77.0369 },
    description: "Bitcoin Policy Institute Summit in Washington DC bringing together policymakers, researchers, and advocates to discuss Bitcoin policy.",
    website: "https://www.btcpolicysummit.org/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 59,
    name: "Bitcoin Zitadelle",
    date: "2025-07-24",
    endDate: "2025-07-27",
    type: "conference",
    location: "Hannover, Germany",
    coordinates: { lat: 52.3759, lng: 9.7320 },
    description: "Bitcoin Zitadelle conference in Hannover, Germany, focusing on building strong Bitcoin fortresses through education and community.",
    website: "https://x.com/BTCZitadelle",
    x: "https://x.com/BTCZitadelle",
    nostr: "",
    featured: false
  },
  {
    id: 60,
    name: "Bitcoin is for Everyone",
    date: "2025-08-01",
    endDate: "2025-08-01",
    type: "meetup",
    location: "Portland, Oregon, USA",
    coordinates: { lat: 45.5152, lng: -122.6784 },
    description: "Bitcoin is for Everyone meetup in Portland promoting Bitcoin accessibility and adoption across all demographics.",
    website: "http://www.bitcoinisforeveryone.com",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 61,
    name: "Lake Satoshi Campout",
    date: "2025-08-02",
    endDate: "2025-08-02",
    type: "meetup",
    location: "Lansing, Michigan, USA",
    coordinates: { lat: 42.7325, lng: -84.5555 },
    description: "Lake Satoshi Campout in Lansing combining outdoor activities with Bitcoin education and community building.",
    website: "https://twitter.com/LakeSatoshi",
    x: "https://twitter.com/LakeSatoshi",
    nostr: "",
    featured: false
  },
  {
    id: 62,
    name: "Budapest Bitcoin",
    date: "2025-08-08",
    endDate: "2025-08-09",
    type: "conference",
    location: "Budapest, Hungary",
    coordinates: { lat: 47.4979, lng: 19.0402 },
    description: "Budapest Bitcoin conference bringing together the Hungarian Bitcoin community for education, networking, and adoption discussions.",
    website: "https://budapestbitcoin.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 63,
    name: "Bitcoin Treasuries Digital Conference",
    date: "2025-08-12",
    endDate: "2025-08-12",
    type: "conference",
    location: "Online",
    coordinates: null,
    description: "Digital conference focusing on Bitcoin treasuries, corporate adoption, and institutional investment strategies.",
    website: "https://lu.ma/qt9p5v1g",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 64,
    name: "Learning Bitcoin",
    date: "2025-08-16",
    endDate: "2025-08-17",
    type: "conference",
    location: "Vancouver, Canada",
    coordinates: { lat: 49.2827, lng: -123.1207 },
    description: "Learning Bitcoin conference in Vancouver focusing on Bitcoin education, skill development, and knowledge sharing.",
    website: "https://www.learningbitcoin.ca/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 65,
    name: "Bitcoin Asia",
    date: "2025-08-28",
    endDate: "2025-08-29",
    type: "conference",
    location: "Hong Kong, China",
    coordinates: { lat: 22.3193, lng: 114.1694 },
    description: "Bitcoin Asia conference in Hong Kong bringing together the Asian Bitcoin community for education, networking, and adoption discussions.",
    website: "https://b.tc/conference/asia",
    x: "https://x.com/TheBitcoinConf",
    nostr: "",
    featured: false
  },
  {
    id: 66,
    name: "Bitcoin Indonesia Conference + Bitcoin Bali Week",
    date: "2025-09-05",
    endDate: "2025-09-05",
    type: "conference",
    location: "Bali, Indonesia",
    coordinates: { lat: -8.3405, lng: 115.0920 },
    description: "Bitcoin Indonesia Conference combined with Bitcoin Bali Week, bringing together the Indonesian Bitcoin community in beautiful Bali.",
    website: "http://bitcoinweekbali.xyz",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 67,
    name: "Accelerating Bitcoin",
    date: "2025-09-15",
    endDate: "2025-09-16",
    type: "conference",
    location: "Asuncion, Paraguay",
    coordinates: { lat: -25.2637, lng: -57.5759 },
    description: "Accelerating Bitcoin conference in Asuncion focusing on speeding up Bitcoin adoption and development in Paraguay and Latin America.",
    website: "https://acelerandobitcoin.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 68,
    name: "Bitcoin Treasuries NYC Unconference",
    date: "2025-09-17",
    endDate: "2025-09-17",
    type: "conference",
    location: "New York City, New York, USA",
    coordinates: { lat: 40.7128, lng: -74.0060 },
    description: "Unconference format Bitcoin Treasuries event in NYC focusing on corporate Bitcoin adoption and treasury management.",
    website: "https://lu.ma/z176rgsb?tk=MPliHW",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 69,
    name: "BTCinDC",
    date: "2025-09-30",
    endDate: "2025-10-01",
    type: "conference",
    location: "Washington DC, USA",
    coordinates: { lat: 38.9072, lng: -77.0369 },
    description: "BTCinDC conference in Washington DC bringing Bitcoin education and advocacy to the nation's capital.",
    website: "https://btcindc.com",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 70,
    name: "MassAdoption",
    date: "2025-10-10",
    endDate: "2025-10-13",
    type: "conference",
    location: "New Hampshire, USA",
    coordinates: { lat: 43.1939, lng: -71.5724 },
    description: "MassAdoption conference in New Hampshire focusing on mass Bitcoin adoption strategies and community building.",
    website: "https://www.campnakamoto.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 71,
    name: "TABConf",
    date: "2025-10-13",
    endDate: "2025-10-16",
    type: "conference",
    location: "Atlanta, Georgia, USA",
    coordinates: { lat: 33.7490, lng: -84.3880 },
    description: "TABConf in Atlanta focusing on Bitcoin development, innovation, and technical discussions.",
    website: "https://tabconf.com/",
    x: "https://x.com/tabconf",
    nostr: "",
    featured: false
  },
  {
    id: 72,
    name: "Bitcoin Alpha",
    date: "2025-10-16",
    endDate: "2025-10-17",
    type: "conference",
    location: "Santa Monica, California, USA",
    coordinates: { lat: 34.0195, lng: -118.4912 },
    description: "Bitcoin Alpha conference in Santa Monica focusing on early-stage Bitcoin projects, innovation, and alpha opportunities.",
    website: "https://bitcoinalpha.org/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 73,
    name: "Canadian Bitcoin Conference",
    date: "2025-10-16",
    endDate: "2025-10-18",
    type: "conference",
    location: "Montreal, Canada",
    coordinates: { lat: 45.5017, lng: -73.5673 },
    description: "Canadian Bitcoin Conference in Montreal bringing together the Canadian Bitcoin community for education, networking, and adoption discussions.",
    website: "https://canadianbitcoinconf.com/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 74,
    name: "Bitcoin Treasuries Digital Conference (October)",
    date: "2025-10-21",
    endDate: "2025-10-21",
    type: "conference",
    location: "Online",
    coordinates: null,
    description: "October edition of the Bitcoin Treasuries Digital Conference focusing on corporate Bitcoin adoption and treasury management.",
    website: "",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 75,
    name: "Bitcoin Dev Summit by Vinteum",
    date: "2025-11-05",
    endDate: "2025-11-05",
    type: "conference",
    location: "São Paulo, Brazil",
    coordinates: { lat: -23.5505, lng: -46.6333 },
    description: "Bitcoin Dev Summit by Vinteum in São Paulo focusing on Bitcoin development, innovation, and technical discussions.",
    website: "",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 76,
    name: "Bitchill 🏝️ retreat",
    date: "2025-11-18",
    endDate: "2025-11-25",
    type: "retreat",
    location: "Roatan, Honduras",
    coordinates: { lat: 16.3000, lng: -86.5500 },
    description: "Bitchill retreat in Roatan combining Bitcoin education with tropical island relaxation and community building.",
    website: "https://lu.ma/swx92134",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 77,
    name: "BUIDL@Tokyo Bitcoin Base (Dev Day)",
    date: "2025-11-23",
    endDate: "2025-11-23",
    type: "conference",
    location: "Tokyo, Japan",
    coordinates: { lat: 35.6762, lng: 139.6503 },
    description: "BUIDL@Tokyo Bitcoin Base Dev Day focusing on Bitcoin development, building, and innovation in Tokyo.",
    website: "https://btc-jpn.com",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 78,
    name: "Bitcoin Japan",
    date: "2025-11-24",
    endDate: "2025-11-24",
    type: "conference",
    location: "Tokyo, Japan",
    coordinates: { lat: 35.6762, lng: 139.6503 },
    description: "Bitcoin Japan conference in Tokyo bringing together the Japanese Bitcoin community for education, networking, and adoption discussions.",
    website: "https://btc-jpn.com",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 79,
    name: "Economía Bitcoin 2025",
    date: "2025-11-22",
    endDate: "2025-11-23",
    type: "conference",
    location: "Berlin, El Salvador",
    coordinates: { lat: 13.4987, lng: -88.5308 },
    description: "Economía Bitcoin 2025 conference in Berlin, El Salvador focusing on Bitcoin economics, adoption, and the future of Bitcoin in El Salvador.",
    website: "https://www.bitcoinberlinsv.com/economia-bitcoin-2025",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 80,
    name: "Africa Bitcoin Conference",
    date: "2025-12-03",
    endDate: "2025-12-05",
    type: "conference",
    location: "Port Louis, Mauritius",
    coordinates: { lat: -20.1609, lng: 57.5012 },
    description: "Africa Bitcoin Conference in Mauritius bringing together the African Bitcoin community for education, networking, and adoption discussions.",
    website: "https://www.afrobitcoin.org/",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 81,
    name: "Mayan Bitcoin Conference",
    date: "2025-12-05",
    endDate: "2025-12-06",
    type: "conference",
    location: "Merida, Mexico",
    coordinates: { lat: 20.9674, lng: -89.5926 },
    description: "Mayan Bitcoin Conference in Merida combining ancient Mayan culture with modern Bitcoin technology and adoption.",
    website: "https://www.mayanbitcoinconference.com",
    x: "",
    nostr: "",
    featured: false
  },
  {
    id: 82,
    name: "Bitcoin MENA",
    date: "2025-12-08",
    endDate: "2025-12-09",
    type: "conference",
    location: "Abu Dhabi, UAE",
    coordinates: { lat: 24.4539, lng: 54.3773 },
    description: "Bitcoin MENA conference in Abu Dhabi bringing together the Middle East and North Africa Bitcoin community.",
    website: "https://b.tc/conference/mena",
    x: "https://x.com/TheBitcoinConf",
    nostr: "",
    featured: false
  },
  {
    id: 83,
    name: "bitcoin++ stands sovereign",
    date: "2025-12-15",
    endDate: "2025-12-17",
    type: "conference",
    location: "Taipei, Taiwan",
    coordinates: { lat: 25.0330, lng: 121.5654 },
    description: "bitcoin++ stands sovereign conference in Taipei focusing on Bitcoin sovereignty, independence, and self-determination.",
    website: "https://btcplusplus.dev/conf/taipei",
    x: "https://x.com/btcplusplus",
    nostr: "",
    featured: false
  },
  {
    id: 84,
    name: "Bitcoin Histórico",
    date: "2025-11-12",
    endDate: "2025-11-13",
    type: "conference",
    location: "San Salvador, El Salvador",
    coordinates: { lat: 13.6929, lng: -89.2182 },
    description: "A conference by the National Bitcoin Office of El Salvador celebrating financial freedom in the heart of San Salvador. Features keynote speeches, panels, workshops, and freedom-tech demos across historic landmarks including the National Palace, National Theater, and BINAES.",
    website: "https://bitcoinhistorico.com/",
    x: "",
    nostr: "",
    featured: false
  }
];
